//import bcrypt from 'bcryptjs';

const data = {
  // users: [
  //   {
  //     name: 'John',
  //     email: 'admin@example.com',
  //     password: bcrypt.hashSync('123456'),
  //     isAdmin: true,
  //   },
  //   {
  //     name: 'Jane',
  //     email: 'user@example.com',
  //     password: bcrypt.hashSync('123456'),
  //     isAdmin: false,
  //   },
  // ],
  products: [
    {
      name: "Blue Buffalo",
      slug: "blue-buffalo",
      category: "DogFood",
      image: "/shop/dog1.jpg",
      price: 19.98,
      brand: "Wilderness",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        "Blue Buffalo Wilderness High Protein Chicken Dry Dog Food for Adult Dogs, Grain-Free, 4.5 lb. Bag",
      isFeatured: true,
      banner: "/shop/banner1.jpg",
    },
    {
      name: "Hypo Premium",
      slug: "hypo-premium",
      category: "DogFood",
      image: "/shop/dog2.jpg",
      price: 132.0,
      brand: "Hypo",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description:
        "Hypro Premium with Kangaroo & Turkey Grain Free is a precisely balanced, all-natural, endurance formula for active and working dogs. It is fully packed with real meat proteins and high-quality fats to promote sustained energy.",
      isFeatured: true,
      banner: "/shop/banner2.jpg",
    },
    {
      name: "IAMS Dog Food",
      slug: "IAMS",
      category: "DogFood",
      image: "/shop/dog3.jpg",
      price: 48.86,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description:
        "Your active big dog is one-of-a-kind… thats why IAMS makes a dry dog food thats just as unique as they are. IAMS Adult Large Breed Dry Dog Food with Real Chicken is formulated to support large breed active dogs by maintaining bone and joint health. With real, farm-raised chicken as the first ingredient, this dry dog food helps provide joint support, while a tailored blend of wholesome fibers and prebiotics promotes healthy digestion and immunity.",
    },
    {
      name: "REFLEX ADULT CAT FOOD",
      slug: "reflex-cat-food",
      category: "CatFood",
      image: "/shop/cat1.jpg",
      price: 45.98,
      brand: "Reflex",
      rating: 3,
      numReviews: 3,
      countInStock: 20,
      description:
        "Daily ration can vary linked to ambient temperature, cat’s lifestyle (indoor-outdoor), temperament and activity. In order to ensure ideal body weight of your cat, weigh out the quantity of food. To provide the correct portions, assess your cat’s appetite, visual appearance and stools. Switch over from one food to another should be done gradually by mixing small amounts of both foods during a period of one week. Ensure that your cat has permanent access to fresh water. Even if the water seems clear, change it at least daily. Keep the product in a dry and cool place and be sure the food bag is properly closed after each feeding.",
      isFeatured: true,
      banner: "/shop/banner1.jpg",
    },
    {
      name: "Reflex Chicken Cat Food",
      slug: "reflex-cat",
      category: "CatFood",
      image: "/shop/cat2.jpg",
      price: 66.68,
      brand: "Reflex",
      rating: 6,
      numReviews: 10,
      countInStock: 20,
      description:
        "Processed Animal Protein, Wheat, Corn, Animal Fat, Wheat Middlings, Corn Gluten, Dried Sugar Beet, Chicken Liver Aroma, Salt, Flaxseed, Dried Brewer’s Yeast, Taurine.",
      isFeatured: true,
      banner: "/shop/banner1.jpg",
    },
    {
      name: "Felix Beef Cat Food",
      slug: "felix-beef",
      category: "CatFood",
      image: "/shop/cat3.jpg",
      price: 75.22,
      brand: "Felix",
      rating: 4,
      numReviews: 8,
      countInStock: 0,
      description: "Felix Beef In Jelly Wet Cat Food 100 Gm",
      isFeatured: true,
      banner: "/shop/banner1.jpg",
    },
    {
      name: "Royal Canin Feline Health for Kittens",
      slug: "RC-Feline",
      category: "CatFood",
      image: "/shop/cat4.jpg",
      price: 83.52,
      brand: "Wilderness",
      rating: 5.5,
      numReviews: 12,
      countInStock: 20,
      description:
        "Royal Canin Feline Health Nutrition Kitten In Jelly Pouch Cat Food is a nutritionally complete & balanced wet diet formulated for kittens aged up to 12 months old. Consisting of thin juicy slices enveloped in jelly, Royal Canin Feline Health Nutrition Kitten In Jelly Pouch Cat Food is easy for kittens to consume. Price listed is for a box of 12 packs x 85g. Formulated for kittens aged up to 12 months old.Easy-to-eat thin juicy slices in jelly.",
      isFeatured: true,
      banner: "/shop/banner1.jpg",
    },
    {
      name: "Cat Carrier",
      slug: "capri-reflex",
      category: "Cat Accessories",
      image: "/shop/capri.jpg",
      price: 50.22,
      brand: "Reflex",
      rating: 8,
      numReviews: 10,
      countInStock: 2,
      description:
        "Carrier for your cat or other small pet. This pet carrier is ideal for the transport of cats, small dogs and other small animals, for example, when going to the vet. It has a holder for car seat belts, making the transport safer. Ventilation slits provide optimal air circulation.",
      isFeatured: true,
      banner: "/shop/banner1.jpg",
    },
  ],

  userdata: {
    id: "11",
    email: "gohar@ucp.edu.pk",
    pass: "******",
    firstname: "gohar",
    lastname: "hayyat",
    phone: "+92-3467178009",

    // id: "22",
    // email: "baloch@ucp.edu.pk",
    // pass: "******",
    // firstname: "abdullah",
    // lastname: "baloch",
    // phone: "+92-123456789",

    // id: "33",
    // email: "owais@ucp.edu.pk",
    // pass: "******",
    // firstname: "agha",
    // lastname: "owais",
    // phone: "+92-987654321",
  },

  pets_data: [
    {
      id: "1",
      userid: "11",
      name: "gohar's Pet_1",
      weight: "1.5",
      daycare: 3,
      vaccinated: true,
      vaccinatedVerified: true,
      breed: "german",
      gender: true,
      type: true,
      month: 3,
      year: 8,
      incurrence: true,
      imageUrl:
        "https://images.pexels.com/photos/3687770/pexels-photo-3687770.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "2",
      userid: "11",
      name: "gohar's Pet_2",
      weight: "1.5",
      daycare: 3,
      vaccinated: true,
      vaccinatedVerified: false,
      breed: "Siberian Husky",
      gender: true,
      type: true,
      month: 3,
      year: 8,
      incurrence: false,
      imageUrl:
        "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
    },
    {
      id: "3",
      userid: "11",
      name: "gohar's Pet_3",
      weight: "1.5",
      daycare: 3,
      vaccinated: true,
      vaccinatedVerified: true,
      breed: "Golden Retriever",
      gender: true,
      type: true,
      month: 3,
      year: 8,
      incurrence: false,
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQS-j0PHXvVcf5PZCiGMawIJoGslbxZxA2NOeuf9uzU&s",
    },

    {
      id: "4",
      userid: "11",
      name: "gohar's Pet_4",
      weight: "1.5",
      daycare: 3,
      vaccinated: true,
      vaccinatedVerified: true,
      breed: "german",
      gender: true,
      type: true,
      month: 3,
      year: 8,
      incurrence: true,
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQS-j0PHXvVcf5PZCiGMawIJoGslbxZxA2NOeuf9uzU&s",
    },
    {
      id: "5",
      userid: "22",
      name: "Abdullah's pet_1",
      weight: "1.5",
      daycare: 3,
      vaccinated: true,
      vaccinatedVerified: true,
      breed: "Golden Retriever",
      gender: true,
      type: true,
      month: 3,
      year: 8,
      incurrence: false,
      imageUrl:
        "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
    },
    {
      id: "6",
      userid: "22",
      name: "Abdullah's pet_2",
      weight: "1.5",
      daycare: 3,
      vaccinated: 0,
      vaccinatedVerified: 0,
      breed: "Siberian Husky",
      gender: true,
      type: true,
      month: 3,
      year: 8,
      incurrence: false,
      imageUrl:
        "https://images.pexels.com/photos/3687770/pexels-photo-3687770.jpeg?auto=compress&cs=tinysrgb&w=600",
    },

    {
      id: "7",
      userid: "33",
      name: "Owais's pet_1",
      weight: "1.5",
      daycare: 3,
      vaccinated: 1,
      vaccinatedVerified: 1,
      breed: "german",
      gender: true,
      type: true,
      month: 3,
      year: 8,
      incurrence: true,
      imageUrl:
        "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
    },
    {
      id: "8",
      userid: "33",
      name: "Owais's pet_1",
      weight: "1.5",
      daycare: 3,
      vaccinated: 1,
      vaccinatedVerified: 0,
      breed: "Siberian Husky",
      gender: true,
      type: true,
      month: 3,
      year: 8,
      incurrence: false,
      imageUrl:
        "https://images.pexels.com/photos/2607544/pexels-photo-2607544.jpeg?cs=srgb&dl=pexels-simona-kidri%C4%8D-2607544.jpg&fm=jpg",
    },
    {
      id: "9",
      userid: "33",
      name: "Owais's pet_1",
      weight: "1.5",
      daycare: 3,
      vaccinated: 0,
      vaccinatedVerified: 0,
      breed: "Golden Retriever",
      gender: true,
      type: true,
      month: 3,
      year: 8,
      incurrence: false,
      imageUrl:
        "https://images.pexels.com/photos/3687770/pexels-photo-3687770.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
  ],
  daycarerequest: [
    {
      // ////////////////////////////////////////
      id: "1",
      identity_number: "1298",
      userid: "11",
      petid: "1",
      toaldays: "3",
      pickuptime: "5",
      pickupcity: "Lahore",
      pickupadress: "207 R-Block Modeltown",
      pickupzip: "4700",
      dropoffcity: "Lahore",
      dropoffadress: "207 R-Block Modeltown",
      dropoffzip: "4700",
      approvedcheck: true,
      requestrejected: false,
      pickedupstatus: true,
      pickupdate: "05/18/2023",
      //drop off data
      dropoffstatus: true,
      dropoffdate: "05/24/2023",
      daysservise: "7",
      bill: "6300RS",
      dropofftime: "5",
      delivered: true,
    },
    {
      id: "2",
      identity_number: "1295",
      userid: "11",
      petid: "2",
      toaldays: "1",
      pickuptime: "1",
      pickupcity: "pakpattan",
      pickupadress: "b 102",
      pickupzip: "5555",
      dropoffcity: "pakpattan",
      dropoffadress: "pakpatttan",
      dropoffzip: "5555",
      approvedcheck: true,
      requestrejected: false,
      pickedupstatus: false,
      pickupdate: "0/0/0",
    },
    {
      id: "3",
      identity_number: "1298",
      userid: "11",
      petid: "3",
      toaldays: "1",
      pickuptime: "1",
      pickupcity: "lhr",
      pickupadress: "55 gulshan ravi",
      pickupzip: "4700",
      dropoffcity: "lhr",
      dropoffadress: "55 gulshan ravi",
      dropoffzip: "4700",
      approvedcheck: false,
      requestrejected: false,
      pickedupstatus: false,
      pickupdate: "0/0/0",
    },
    {
      id: "4",
      identity_number: "1228",
      userid: "11",
      petid: "4",
      toaldays: "1",
      pickuptime: "1",
      pickupcity: "lhr",
      pickupadress: "55 gulshan ravi",
      pickupzip: "4700",
      dropoffcity: "lhr",
      dropoffadress: "55 gulshan ravi",
      dropoffzip: "4700",
      approvedcheck: false,
      requestrejected: true,
      pickedupstatus: false,
      pickupdate: "0/0/0",
    },
  ],
};

export default data;
